version: "2"
services:
   dbb:
     image: postgres 
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_PASSWORD=postgres
   webb:
     build: .
     ports:
       - "80:3000"
     depends_on: 
       - dbb 