FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash
RUN apt-get install -y  nodejs
RUN apt-get install -y git
RUN git clone https://github.com/CORE-UPM/CRM_2017
WORKDIR CRM_2017
RUN npm install 
RUN npm run-script migrate_local
RUN npm run-script seed_local
EXPOSE 3000
CMD ["npm run-script supervisor"]
